name: allm

services:
  postgres:
    image: postgres:17
    command: ['postgres', '-c', 'log_statement=all']
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
